export const currencies = [
  { code: "USD", name: "US Dollar", symbol: "$", country: "United States" },
  { code: "EUR", name: "Euro", symbol: "€", country: "European Union" },
  { code: "GBP", name: "British Pound", symbol: "£", country: "United Kingdom" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", country: "Japan" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$", country: "Australia" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", country: "Canada" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF", country: "Switzerland" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥", country: "China" },
  { code: "INR", name: "Indian Rupee", symbol: "₹", country: "India" },
  { code: "MXN", name: "Mexican Peso", symbol: "$", country: "Mexico" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", country: "Brazil" },
  { code: "ZAR", name: "South African Rand", symbol: "R", country: "South Africa" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽", country: "Russia" },
  { code: "KRW", name: "South Korean Won", symbol: "₩", country: "South Korea" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", country: "Singapore" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", country: "Hong Kong" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", country: "Norway" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr", country: "Sweden" },
  { code: "DKK", name: "Danish Krone", symbol: "kr", country: "Denmark" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł", country: "Poland" },
  { code: "THB", name: "Thai Baht", symbol: "฿", country: "Thailand" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", country: "Indonesia" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", country: "Hungary" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", country: "Czech Republic" },
  { code: "ILS", name: "Israeli Shekel", symbol: "₪", country: "Israel" },
  { code: "CLP", name: "Chilean Peso", symbol: "$", country: "Chile" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", country: "Philippines" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ", country: "United Arab Emirates" },
  { code: "COP", name: "Colombian Peso", symbol: "$", country: "Colombia" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼", country: "Saudi Arabia" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", country: "Malaysia" },
  { code: "RON", name: "Romanian Leu", symbol: "lei", country: "Romania" },
  { code: "ARS", name: "Argentine Peso", symbol: "$", country: "Argentina" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫", country: "Vietnam" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", country: "Bulgaria" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", country: "Turkey" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn", country: "Croatia" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", country: "New Zealand" },
  { code: "EGP", name: "Egyptian Pound", symbol: "£", country: "Egypt" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨", country: "Pakistan" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", country: "Nigeria" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", country: "Bangladesh" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", country: "Ukraine" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", country: "Kenya" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/", country: "Peru" },
  { code: "QAR", name: "Qatari Riyal", symbol: "﷼", country: "Qatar" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", country: "Kuwait" },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", country: "Morocco" },
  { code: "TWD", name: "Taiwan Dollar", symbol: "NT$", country: "Taiwan" },
  { code: "ISK", name: "Icelandic Króna", symbol: "kr", country: "Iceland" },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", country: "Jordan" },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "Rs", country: "Sri Lanka" },
  { code: "OMR", name: "Omani Rial", symbol: "﷼", country: "Oman" },
  { code: "BHD", name: "Bahraini Dinar", symbol: ".د.ب", country: "Bahrain" },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", country: "Ghana" },
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", country: "Tanzania" },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh", country: "Uganda" },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", country: "Ethiopia" },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", country: "Algeria" },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", country: "Tunisia" },
  { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", country: "Lebanon" },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", country: "Iraq" },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋", country: "Afghanistan" },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K", country: "Myanmar" },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", country: "Cambodia" },
  { code: "LAK", name: "Lao Kip", symbol: "₭", country: "Laos" },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨", country: "Nepal" },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", country: "Maldives" },
  { code: "BND", name: "Brunei Dollar", symbol: "B$", country: "Brunei" },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$", country: "Fiji" },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", country: "Papua New Guinea" },
  { code: "WST", name: "Samoan Tala", symbol: "T", country: "Samoa" },
  { code: "TOP", name: "Tongan Paʻanga", symbol: "T$", country: "Tonga" },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "VT", country: "Vanuatu" },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "SI$", country: "Solomon Islands" },
  { code: "MOP", name: "Macanese Pataca", symbol: "MOP$", country: "Macau" },
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", country: "Kazakhstan" },
  { code: "UZS", name: "Uzbekistani Som", symbol: "so'm", country: "Uzbekistan" },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", country: "Georgia" },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", country: "Armenia" },
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", country: "Azerbaijan" },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", country: "Belarus" },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", country: "Moldova" },
  { code: "RSD", name: "Serbian Dinar", symbol: "дин", country: "Serbia" },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден", country: "North Macedonia" },
  { code: "ALL", name: "Albanian Lek", symbol: "L", country: "Albania" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM", country: "Bosnia and Herzegovina" },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡", country: "Costa Rica" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", country: "Guatemala" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", country: "Honduras" },
  { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", country: "Nicaragua" },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", country: "Panama" },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", country: "Dominican Republic" },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$", country: "Jamaica" },
  { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$", country: "Trinidad and Tobago" },
  { code: "BBD", name: "Barbadian Dollar", symbol: "Bds$", country: "Barbados" },
  { code: "BSD", name: "Bahamian Dollar", symbol: "B$", country: "Bahamas" },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$", country: "Belize" },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs.", country: "Bolivia" },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "₲", country: "Paraguay" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", country: "Uruguay" },
  { code: "VES", name: "Venezuelan Bolívar", symbol: "Bs.", country: "Venezuela" },
  { code: "GYD", name: "Guyanese Dollar", symbol: "G$", country: "Guyana" },
  { code: "SRD", name: "Surinamese Dollar", symbol: "$", country: "Suriname" },
  { code: "AWG", name: "Aruban Florin", symbol: "ƒ", country: "Aruba" },
  { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ", country: "Curaçao" },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "EC$", country: "Eastern Caribbean" },
  { code: "HTG", name: "Haitian Gourde", symbol: "G", country: "Haiti" },
  { code: "CUP", name: "Cuban Peso", symbol: "$", country: "Cuba" },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨", country: "Mauritius" },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨", country: "Seychelles" },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", country: "Madagascar" },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK", country: "Malawi" },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", country: "Zambia" },
  { code: "BWP", name: "Botswana Pula", symbol: "P", country: "Botswana" },
  { code: "NAD", name: "Namibian Dollar", symbol: "N$", country: "Namibia" },
  { code: "SZL", name: "Swazi Lilangeni", symbol: "L", country: "Eswatini" },
  { code: "LSL", name: "Lesotho Loti", symbol: "L", country: "Lesotho" },
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", country: "Angola" },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT", country: "Mozambique" },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "Z$", country: "Zimbabwe" },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw", country: "Rwanda" },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu", country: "Burundi" },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj", country: "Djibouti" },
  { code: "SOS", name: "Somali Shilling", symbol: "Sh", country: "Somalia" },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", country: "Eritrea" },
  { code: "SDG", name: "Sudanese Pound", symbol: "ج.س.", country: "Sudan" },
  { code: "SSP", name: "South Sudanese Pound", symbol: "£", country: "South Sudan" },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", country: "Libya" },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM", country: "Mauritania" },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", country: "Gambia" },
  { code: "SLL", name: "Sierra Leonean Leone", symbol: "Le", country: "Sierra Leone" },
  { code: "LRD", name: "Liberian Dollar", symbol: "L$", country: "Liberia" },
  { code: "GNF", name: "Guinean Franc", symbol: "FG", country: "Guinea" },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "$", country: "Cape Verde" },
  { code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db", country: "São Tomé and Príncipe" },
  { code: "XOF", name: "West African CFA Franc", symbol: "CFA", country: "West Africa" },
  { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA", country: "Central Africa" },
  { code: "KMF", name: "Comorian Franc", symbol: "CF", country: "Comoros" },
  { code: "CDF", name: "Congolese Franc", symbol: "FC", country: "Democratic Republic of Congo" },
  { code: "XPF", name: "CFP Franc", symbol: "₣", country: "French Pacific" },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼", country: "Yemen" },
  { code: "SYP", name: "Syrian Pound", symbol: "£S", country: "Syria" },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "m", country: "Turkmenistan" },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "ЅМ", country: "Tajikistan" },
  { code: "KGS", name: "Kyrgyzstani Som", symbol: "с", country: "Kyrgyzstan" },
  { code: "MNT", name: "Mongolian Tögrög", symbol: "₮", country: "Mongolia" },
  { code: "KPW", name: "North Korean Won", symbol: "₩", country: "North Korea" },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", country: "Bhutan" },
];
