import { Template, checkTemplate } from "@pdfme/common";

export const invoiceTemplate: Template = {
  schemas: [
    [
      {
        name: "companyName",
        type: "text",
        position: { x: 20, y: 20 },
        width: 100,
        height: 10,
        fontSize: 20,
      },
      {
        name: "invoiceTitle",
        type: "text",
        position: { x: 150, y: 20 },
        width: 40,
        height: 10,
        fontSize: 20,
        alignment: "right",
      },
      {
        name: "invoiceNumberLabel",
        type: "text",
        position: { x: 150, y: 30 },
        width: 20,
        height: 5,
        fontSize: 9,
        content: "Invoice No:",
      },
      {
        name: "invoiceNumber",
        type: "text",
        position: { x: 170, y: 30 },
        width: 20,
        height: 5,
        fontSize: 9,
        alignment: "right",
      },
      {
        name: "dateLabel",
        type: "text",
        position: { x: 150, y: 35 },
        width: 20,
        height: 5,
        fontSize: 9,
        content: "Date:",
      },
      {
        name: "date",
        type: "text",
        position: { x: 170, y: 35 },
        width: 20,
        height: 5,
        fontSize: 9,
        alignment: "right",
      },
      {
        name: "dueDateLabel",
        type: "text",
        position: { x: 150, y: 40 },
        width: 20,
        height: 5,
        fontSize: 9,
        content: "Due Date:",
      },
      {
        name: "dueDate",
        type: "text",
        position: { x: 170, y: 40 },
        width: 20,
        height: 5,
        fontSize: 9,
        alignment: "right",
      },
      
      {
        name: "billToLabel",
        type: "text",
        position: { x: 20, y: 50 },
        width: 50,
        height: 5,
        fontSize: 10,
        content: "Bill To:",
      },
      {
        name: "clientName",
        type: "text",
        position: { x: 20, y: 56 },
        width: 80,
        height: 6,
        fontSize: 12,
      },
      {
        name: "clientAddress",
        type: "text",
        position: { x: 20, y: 63 },
        width: 80,
        height: 20,
        fontSize: 9,
      },

      // Items Table Header
      {
        name: "th_desc",
        type: "text",
        position: { x: 20, y: 90 },
        width: 90,
        height: 7,
        fontSize: 10,
        backgroundColor: "#f3f4f6",
        content: "Description",
      },
      {
        name: "th_qty",
        type: "text",
        position: { x: 110, y: 90 },
        width: 20,
        height: 7,
        fontSize: 10,
        backgroundColor: "#f3f4f6",
        content: "Qty",
        alignment: "center",
      },
      {
        name: "th_price",
        type: "text",
        position: { x: 130, y: 90 },
        width: 30,
        height: 7,
        fontSize: 10,
        backgroundColor: "#f3f4f6",
        content: "Price",
        alignment: "right",
      },
      {
        name: "th_total",
        type: "text",
        position: { x: 160, y: 90 },
        width: 30,
        height: 7,
        fontSize: 10,
        backgroundColor: "#f3f4f6",
        content: "Amount",
        alignment: "right",
      },

      // Items (Placeholder for 10 items)
      ...Array.from({ length: 15 }).map((_, i) => [
        {
          name: `item_desc_${i}`,
          type: "text",
          position: { x: 20, y: 100 + i * 7 },
          width: 90,
          height: 7,
          fontSize: 9,
        },
        {
          name: `item_qty_${i}`,
          type: "text",
          position: { x: 110, y: 100 + i * 7 },
          width: 20,
          height: 7,
          fontSize: 9,
          alignment: "center",
        },
        {
          name: `item_price_${i}`,
          type: "text",
          position: { x: 130, y: 100 + i * 7 },
          width: 30,
          height: 7,
          fontSize: 9,
          alignment: "right",
        },
        {
          name: `item_total_${i}`,
          type: "text",
          position: { x: 160, y: 100 + i * 7 },
          width: 30,
          height: 7,
          fontSize: 9,
          alignment: "right",
        },
      ]).flat(),

      // Totals
      {
        name: "subtotalLabel",
        type: "text",
        position: { x: 140, y: 220 },
        width: 20,
        height: 5,
        fontSize: 9,
        content: "Subtotal:",
        alignment: "right",
      },
      {
        name: "subtotal",
        type: "text",
        position: { x: 165, y: 220 },
        width: 25,
        height: 5,
        fontSize: 9,
        alignment: "right",
      },
      {
        name: "taxLabel",
        type: "text",
        position: { x: 140, y: 226 },
        width: 20,
        height: 5,
        fontSize: 9,
        content: "Tax:",
        alignment: "right",
      },
      {
        name: "tax",
        type: "text",
        position: { x: 165, y: 226 },
        width: 25,
        height: 5,
        fontSize: 9,
        alignment: "right",
      },
      {
        name: "totalLabel",
        type: "text",
        position: { x: 140, y: 235 },
        width: 20,
        height: 7,
        fontSize: 11,
        content: "Total:",
        alignment: "right",
      },
      {
        name: "total",
        type: "text",
        position: { x: 165, y: 235 },
        width: 25,
        height: 7,
        fontSize: 11,
        alignment: "right",
      },

      // Payment Info
      {
        name: "paymentInfoLabel",
        type: "text",
        position: { x: 20, y: 220 },
        width: 80,
        height: 5,
        fontSize: 10,
        content: "Payment Info:",
      },
      {
        name: "paymentInfo",
        type: "text",
        position: { x: 20, y: 226 },
        width: 80,
        height: 40,
        fontSize: 9,
      },
    ],
  ],
  basePdf: {
    width: 210,
    height: 297,
    padding: [10, 10, 10, 10],
  },
};
